### ISSUE TITLE
Error in CLI: unexpected keyword argument 'pathName'

### ISSUE THREAD

**Issue by rmzzz** [resamsel/translatr#96]
```
translatr -L .translatr.log --debug pull; tail -f .translatr.log 
__new__() got an unexpected keyword argument 'pathName'
2017-12-07 14:44:01 DEBUG urllib3.connectionpool: https://translatr.s******.***:443 "GET /api/locales/bd7d****-****-****-****-******84e4?access_token=M2N...N2Qz HTTP/1.1" 200 849
2017-12-07 14:44:01 ERROR __main__: __new__() got an unexpected keyword argument 'pathName'
Traceback (most recent call last):
  File "/usr/local/bin/translatr", line 826, in main
    args.func(args)
  File "/usr/local/bin/translatr", line 455, in pull
    for locale in api.locales():
  File "/usr/local/bin/translatr", line 200, in locales
    ).json()['list']
TypeError: __new__() got an unexpected keyword argument 'pathName'

```
Notes:
-  local script matches current from master
- OS: macOS High Sierra (with default xcode command line tools)
- Python version: 2.7.13

**Comment by resamsel** [comment]
@rmzzz, try using the latest develop version:

```
export TRANSLATR_TAG=develop
curl -fsSL https://raw.githubusercontent.com/resamsel/translatr/develop/install.sh | bash
```
